// Hardcoded content snapshot from the current mad-studio.html, migrated to Sanity.
// Edit these objects to change the first seed, then re-run `npm run seed`.

export const SITE_SETTINGS = {
  tagline: 'where bold ideas meet sharp minds.',
  websiteUrl: 'https://beingmad.co',
  websiteUrlLabel: 'beingmad.co',
  contactEmail: 'madboulyjr.7@gmail.com',
  socials: [
    {label: 'Behance', url: 'https://www.behance.net/madbovlly'},
    {label: 'Instagram', url: 'https://instagram.com/'},
  ],
}

export const SECTIONS = [
  {
    slug: 'originals',
    order: 1,
    title: 'MAD Originals.',
    subtitle: 'The main studio practice.',
    description: 'Art direction, campaigns & visual identity.',
    cardLabel: 'Main Studio · Portfolio',
    landingBg: '#0D0D0D',
    landingAccent: '#FF313B',
    landingHeadline: 'MAD\nORIGINALS.',
    landingSubtitle:
      'ART DIRECTION, CAMPAIGNS & VISUAL IDENTITY. <em>the main studio practice.</em><br>WHERE CONCEPT MEETS CRAFT FOR BRANDS THAT WANT TO STOP SCROLLS.',
    counterLabel: 'Originals',
    kicker: '01 / The Main Practice',
    manifesto: 'Creativity is <em>madness</em> with a deadline.',
    lead:
      'Art direction, campaigns & visual identity for brands that refuse to blend in. <strong>9+ years</strong> dancing with industry giants — Google Arabia, Mondelez, Vodafone, Mazda, Hardee\'s — at AKQA, FP7, Acquaint and Socialeyez.',
    agencies: [
      'Acquaint',
      'Socialeyez Dubai',
      'Google Arabia',
      'Vodafone',
      'Mazda',
      'Mondelez',
      "Hardee's",
      'AKQA (WPP)',
      'FP7 Cairo',
    ],
    worksLabel: 'Selected Works',
    worksTitle: 'A Fine Selection.',
  },
  {
    slug: 'bubble',
    order: 2,
    title: 'MAD Bubble.',
    subtitle: 'Personal art & experiments.',
    description: 'Personal art, experiments & side obsessions.',
    cardLabel: 'Personal Art · Experimental',
    landingBg: '#D0FA51',
    landingAccent: '#584CF5',
    landingHeadline: 'MAD\nBUBBLE.',
    landingSubtitle:
      "IDEAS THAT DON'T FIT THE BRIEF. PERSONAL & EXPERIMENTAL FAN ART.<br>CULTURAL LOVE LETTERS, <em>Things That Exist Just Because They Should.</em>",
    counterLabel: 'Bubble',
    kicker: '02 / Experimental Practice',
    manifesto: 'Normal is <em>over-rated.</em> Be mad.',
    lead: 'The experiments, the obsessions, the pieces that refuse to sit inside the studio brief.',
    agencies: [],
    worksLabel: 'Selected Works',
    worksTitle: 'The Bubble.',
  },
  {
    slug: 'music',
    order: 3,
    title: 'MAD+.',
    subtitle: 'Music production.',
    description: 'Sound, beats & production.',
    cardLabel: 'Music Production',
    landingBg: '#FF313B',
    landingAccent: '#D0FA51',
    landingHeadline: 'MAD+\nMUSIC.',
    landingSubtitle:
      'MAKING MUSIC SINCE I WAS YOUNG. SCORING ADS, FILMS, SERIES.<br>PRODUCING ORIGINALS. DEEP HOUSE, EGYPTIAN INSTRUMENTS, AFRO SOUNDS<br>AUTHENTIC SOUND DIRECTION, <em>No Formula.</em>',
    counterLabel: 'Plus',
    kicker: '03 / The Sonic Practice',
    manifesto: 'The <em>mad</em> ones hear it before it exists.',
    lead: 'Sound, beats & production where the visual practice meets the sonic one.',
    agencies: [],
    worksLabel: 'Selected Tracks',
    worksTitle: 'The Record.',
  },
  {
    slug: 'vision',
    order: 4,
    title: 'MAD Vision.',
    subtitle: 'Video generating · storytelling.',
    description: 'Video generating · storytelling.',
    cardLabel: 'Video · Storytelling',
    landingBg: '#584CF5',
    landingAccent: '#D0FA51',
    landingHeadline: 'MAD\nVISION.',
    landingSubtitle:
      'CREATING ADS, FILMS, SHORTS, MUSIC VIDEOS. AESTHETIC, CONCEPTUAL,<br>EXECUTION-DRIVEN. <em>Using AI Tools To Break Visual Limits,</em><br>THROUGH EXPERIMENTAL PRODUCTION.',
    counterLabel: 'Vision',
    kicker: '04 / The Narrative Practice',
    manifesto: 'Mad <em>isn\'t</em> a problem. It\'s a process.',
    lead: 'Video generation, storytelling & motion — narrative work for brands and self-initiated films.',
    agencies: [],
    worksLabel: 'Selected Work',
    worksTitle: 'Moving Pictures.',
  },
]

export const ORIGINALS_PROJECTS = [
  {slug: 'land-rover',            title: 'Land Rover',            year: '2023', caption: '', tags: ['Art Direction','Digital','OOH'], imgs: ['land-rover.jpg','land-rover-img1.jpg','land-rover-img2.jpg','land-rover-img3.jpg']},
  {slug: 'google-arabia',         title: 'Google Arabia',         year: '2018', caption: 'Ask Google — launching campaign', tags: ['Art Direction','Creative Direction','360 Campaign'], imgs: ['google-arabia.jpg','google-arabia-img1.jpg','google-arabia-img2.jpg','google-arabia-img3.jpg','google-arabia-img4.jpg']},
  {slug: 'biolab',                title: 'BIOLAB',                year: '2024', caption: '', tags: ['Art Direction','3D Design','Creative Direction','360 Campaign'], imgs: ['biolab.jpg','biolab-img1.jpg','biolab-img2.jpg','biolab-img3.jpg','biolab-img4.jpg']},
  {slug: 'bank-aljazira',         title: 'Bank Aljazira',         year: '2024', caption: 'Kingdom of Saudi Arabia', tags: ['Art Direction','3D Viz','Creative Direction','360 Campaign'], imgs: ['bank-aljazira.jpg','bank-aljazira-img1.jpg','bank-aljazira-img2.jpg','bank-aljazira-img3.jpg','bank-aljazira-img4.jpg']},
  {slug: 'vodafone-red',          title: 'Vodafone RED',          year: '2020', caption: 'Premium RED subscription announcement', tags: ['Art Direction','Creative Direction','360 Campaign'], imgs: ['vodafone-red.jpg','vodafone-red-img1.jpg','vodafone-red-img2.jpg','vodafone-red-img3.jpg','vodafone-red-img4.jpg']},
  {slug: 'zain-ksa',              title: 'Zain KSA',              year: '2024', caption: '', tags: ['Art Direction','Creative Direction','Digital'], imgs: ['zain-ksa.jpg','zain-ksa-img1.jpg','zain-ksa-img2.jpg','zain-ksa-img3.jpg','zain-ksa-img4.jpg']},
  {slug: 'jeddah-airports',       title: 'Jeddah Airports',       year: '2024', caption: '', tags: ['Art Direction','3D Viz','Digital'], imgs: ['jeddah-airports.jpg','jeddah-airports-img1.jpg','jeddah-airports-img2.jpg','jeddah-airports-img3.jpg','jeddah-airports-img4.jpg']},
  {slug: 'saudi-games',           title: 'Saudi Games',           year: '2023', caption: '', tags: ['Art Direction','3D Design','Creative Direction','360 Campaign'], imgs: ['saudi-games.jpg','saudi-games-img1.jpg','saudi-games-img2.jpg','saudi-games-img3.jpg','saudi-games-img4.jpg','saudi-games-img5.jpg','saudi-games-img6.jpg','saudi-games-img7.jpg']},
  {slug: 'qiddiya',               title: 'Qiddiya',               year: '2025', caption: 'Kingdom of Saudi Arabia', tags: ['Art Direction','Digital','OOH'], imgs: ['qiddiya.jpg','qiddiya-img1.jpg','qiddiya-img2.jpg','qiddiya-img3.jpg']},
  {slug: 'film-commission',       title: 'Film Commission',       year: '2025', caption: 'Kingdom of Saudi Arabia', tags: ['Art Direction','Digital','OOH'], imgs: ['film-commission.jpg','film-commission-img1.jpg','film-commission-img2.jpg','film-commission-img3.jpg']},
  {slug: 'jb-financial',          title: 'JB Financial',          year: '2025', caption: 'Ramadan campaign × Vimto', tags: ['Art Direction','Creative Direction','360 Campaign'], imgs: ['jb-financial.jpg','jb-financial-img1.jpg','jb-financial-img2.jpg','jb-financial-img3.jpg','jb-financial-img4.jpg','jb-financial-img5.jpg','jb-financial-img6.jpg']},
  {slug: 'atp-next-gen',          title: 'ATP Next Gen',          year: '2024', caption: '', tags: ['Art Direction','Digital','On-Ground Activation'], imgs: ['atp-next-gen.jpg','atp-next-gen-img1.jpg','atp-next-gen-img2.jpg','atp-next-gen-img3.jpg','atp-next-gen-img4.jpg']},
  {slug: 'temmys',                title: "Temmy's",               year: '2021', caption: 'Egypt', tags: ['Art Direction','Creative Direction','360 Campaign'], imgs: ['temmys.jpg','temmys-img1.jpg','temmys-img2.jpg','temmys-img3.jpg','temmys-img4.jpg']},
  {slug: 'citroen',               title: 'Citroën',               year: '2023', caption: 'Egypt', tags: ['Art Direction','Digital','OOH'], imgs: ['citroen.jpg','citroen-img1.jpg','citroen-img2.jpg','citroen-img3.jpg']},
  {slug: 'halwani-bros',          title: 'Halwani Bros',          year: '2023', caption: '"A quality we grew up with" — awareness campaign', tags: ['Art Direction','Creative Direction','360 Campaign'], imgs: ['halwani-bros.jpg','halwani-bros-img1.jpg','halwani-bros-img2.jpg','halwani-bros-img3.jpg','halwani-bros-img4.jpg','halwani-bros-img5.jpg','halwani-bros-img6.jpg']},
  {slug: 'moro',                  title: 'Moro',                  year: '2021', caption: '"Where are you going to put that energy?" — awareness', tags: ['Art Direction','Creative Direction','360 Campaign'], imgs: ['moro.jpg','moro-img1.jpg','moro-img2.jpg','moro-img3.jpg','moro-img4.jpg','moro-img5.jpg']},
  {slug: 'taiba-investments',     title: 'Taiba Investments',     year: '2024', caption: '', tags: ['Art Direction','3D Design','Creative Direction','360 Campaign'], imgs: ['taiba-investments.jpg','taiba-investments-img1.jpg','taiba-investments-img2.jpg','taiba-investments-img3.jpg','taiba-investments-img4.jpg']},
  {slug: 'haval',                 title: 'Haval',                 year: '2021', caption: 'Launch campaign in Egypt', tags: ['Art Direction','Creative Direction','360 Campaign'], imgs: ['haval.jpg','haval-img1.jpg','haval-img2.jpg','haval-img3.jpg','haval-img4.jpg','haval-img5.jpg','haval-img6.jpg']},
  {slug: 'derayah-financial',     title: 'Derayah Financial',     year: '2025', caption: 'Financial mobile app awareness campaign', tags: ['Art Direction','Creative Direction','360 Campaign'], imgs: ['derayah-financial.jpg','derayah-financial-img1.jpg','derayah-financial-img2.jpg','derayah-financial-img3.jpg','derayah-financial-img4.jpg','derayah-financial-img5.jpg','derayah-financial-img6.jpg']},
  {slug: 'derayah-financial-ksa', title: 'Derayah Financial KSA', year: '2025', caption: '', tags: ['Art Direction','3D Viz','Creative Direction','360 Campaign'], imgs: ['derayah-financial-ksa.jpg','derayah-financial-ksa-img1.jpg','derayah-financial-ksa-img2.jpg','derayah-financial-ksa-img3.jpg','derayah-financial-ksa-img4.jpg']},
  {slug: 'general-court-of-audit',title: 'General Court of Audit',year: '2025', caption: '', tags: ['Art Direction','Digital','OOH'], imgs: ['general-court-of-audit.jpg','general-court-of-audit-img1.jpg','general-court-of-audit-img2.jpg','general-court-of-audit-img3.jpg']},
]
