#!/usr/bin/env node
/**
 * Generate the two pixel-art cursor PNGs into /public.
 *
 *   cursor-arrow.png  →  default state. Classic Macintosh/Win98 spear
 *                        arrow. Hotspot (1, 1) at the tip.
 *   cursor-hand.png   →  hover state. Rock-and-roll / devil-horns hand
 *                        (index + pinky up, middle + ring curled,
 *                        thumb tucked across). Hotspot (6, 1) at the
 *                        tip of the index finger.
 *
 * Designed as 32×32 pixel grids in ASCII (`#`/`o`/`.`) and rendered
 * through sharp's raw RGBA path. Pixel-by-pixel control beats vector
 * → raster conversion for sub-32 cursor art.
 */
import sharp from 'sharp'
import path from 'node:path'
import {fileURLToPath} from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PUBLIC = path.resolve(__dirname, '../public')

/* ─── ARROW — tall, slender pixel-spear ───────────────────────────
   Designed to match the classic Mac cursor proportions: long left
   vertical edge, diagonal staircase right edge meeting a wing tab,
   then a detached tail with a foot at the bottom. */
const ARROW = `
##..............................
#o#.............................
#oo#............................
#ooo#...........................
#oooo#..........................
#ooooo#.........................
#oooooo#........................
#ooooooo#.......................
#oooooooo#......................
#ooooooooo#.....................
#oooooooooo#....................
#ooooooooooo#...................
#oooooooooooo#..................
#ooooooooooooo#.................
#oooooooooooooo#................
#oooooooo########...............
#ooooo###oo##...................
#oooo#..#oo##...................
#ooo#...#ooo##..................
#oo#.....#ooo##.................
##.......#oooo##................
..........#oooo##...............
...........#oooo#...............
............####................
................................
................................
................................
................................
................................
................................
................................
................................
`.trim().split('\n').map(r => r.padEnd(32, '.'))

/* ─── ROCK-AND-ROLL HAND — index + pinky up, mid/ring curled ────── */
const HAND = `
......##.........##.............
.....#oo#.......#oo#............
.....#oo#.......#oo#............
.....#oo#.......#oo#............
.....#oo#.......#oo#............
.....#oo#.......#oo#............
.....#oo#.......#oo#............
.....#oo###.....#oo#............
.....#oo#oo#####oo##............
.....#oo#oo#oo##ooo#............
.....#oo#oo#oo#oooo#............
##...#oo#oo#oo#oooo#............
#oo##oo#####ooooooo#............
#oooo##oooooooooooo#............
#oooooooooooooooooo#............
#oooooooooooooooooo#............
.#ooooooooooooooooo#............
.#ooooooooooooooooo#............
..#oooooooooooooooo#............
..#oooooooooooooooo#............
...#ooooooooooooooo#............
...#ooooooooooooooo#............
....####################........
................................
................................
................................
................................
................................
................................
................................
................................
................................
`.trim().split('\n').map(r => r.padEnd(32, '.'))

function gridToBuffer(grid) {
  const W = 32, H = 32
  const buf = Buffer.alloc(W * H * 4)
  for (let y = 0; y < H; y++) {
    const row = grid[y] || ''
    for (let x = 0; x < W; x++) {
      const ch = row[x] || '.'
      const i = (y * W + x) * 4
      if (ch === '#') {
        buf[i] = 0; buf[i+1] = 0; buf[i+2] = 0; buf[i+3] = 255
      } else if (ch === 'o') {
        buf[i] = 255; buf[i+1] = 255; buf[i+2] = 255; buf[i+3] = 255
      } else {
        buf[i] = 0; buf[i+1] = 0; buf[i+2] = 0; buf[i+3] = 0
      }
    }
  }
  return buf
}

async function writePng(name, grid) {
  const raw = gridToBuffer(grid)
  await sharp(raw, {raw: {width: 32, height: 32, channels: 4}})
    .png({compressionLevel: 9})
    .toFile(path.join(PUBLIC, name))
  console.log(`  ✓ ${name}`)
}

await writePng('cursor-arrow.png', ARROW)
await writePng('cursor-hand.png', HAND)
console.log('\n  Both cursors written to /public.\n')
