#!/usr/bin/env node
/**
 * Generate the two pixel-art cursor PNGs (arrow + hand) into public/.
 *
 * Why a script? CSS cursors need real raster PNGs (SVG cursors don't
 * render reliably across Safari + Firefox). Designing them as pixel
 * grids in code is the only way to get the chunky old-school look
 * without aliasing artifacts that a vector-to-raster pass would
 * introduce.
 *
 * Grid legend:
 *   .  →  transparent
 *   #  →  black outline (#000)
 *   o  →  white fill   (#FFF)
 *
 * The arrow is 32×32 with hotspot (1, 1) — tip of the spear.
 * The hand  is 32×32 with hotspot (10, 1) — tip of the index finger.
 */
import sharp from 'sharp'
import path from 'node:path'
import {fileURLToPath} from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PUBLIC = path.resolve(__dirname, '../public')

/* ─── ARROW — 32x32 pixel-art Macintosh-style cursor ──────────────── */
const ARROW = `
#...............................
##..............................
#o#.............................
#oo#............................
#ooo#...........................
#oooo#..........................
#ooooo#.........................
#oooooo#........................
#ooooooo#.......................
#oooooooo#......................
#ooooooooo#.....................
#oooooooooo#....................
#ooooooooooo#...................
#oooooooooooo#..................
#ooooooooooooo#.................
#oooooooooooooo#................
#ooooooooo######................
#oooooo###o##...................
#oooo##.#oo##...................
#oo##...#ooo##..................
##......##ooo##.................
.........##ooo##................
..........##ooo##...............
...........##ooo##..............
............##ooo##.............
.............##oo##.............
..............####..............
................................
................................
................................
................................
................................
`.trim().split('\n').map(r => r.padEnd(32, '.'))

/* ─── HAND — 32x32 pixel-art pointing-hand cursor ────────────────── */
const HAND = `
..........##....................
.........#oo#...................
.........#oo#...................
.........#oo#...................
.........#oo#...................
.........#oo#...................
.........#oo####................
.........#oo#oo###..............
.........#oo#oo#oo##............
.........#oo#oo#oo#oo##.........
####.....#oo#oo#oo#oo#oo#.......
#oo##....#oooooooooooooo#.......
#ooo#....#oooooooooooooo#.......
#oooo#...#oooooooooooooo#.......
#ooooo###oooooooooooooooo#......
#ooooooo#ooooooooooooooo#.......
.#oooooooooooooooooooooo#.......
.#ooooooooooooooooooooo#........
..#oooooooooooooooooooo#........
..#oooooooooooooooooooo#........
...#ooooooooooooooooooo#........
...#ooooooooooooooooooo#........
....######################......
................................
................................
................................
................................
................................
................................
................................
................................
................................
`.trim().split('\n').map(r => r.padEnd(32, '.'))

function gridToBuffer(grid) {
  const W = 32, H = 32
  const buf = Buffer.alloc(W * H * 4)
  for (let y = 0; y < H; y++) {
    const row = grid[y] || ''
    for (let x = 0; x < W; x++) {
      const ch = row[x] || '.'
      const i = (y * W + x) * 4
      if (ch === '#') {
        buf[i] = 0; buf[i+1] = 0; buf[i+2] = 0; buf[i+3] = 255
      } else if (ch === 'o') {
        buf[i] = 255; buf[i+1] = 255; buf[i+2] = 255; buf[i+3] = 255
      } else {
        buf[i] = 0; buf[i+1] = 0; buf[i+2] = 0; buf[i+3] = 0
      }
    }
  }
  return buf
}

async function writePng(name, grid) {
  const raw = gridToBuffer(grid)
  await sharp(raw, {raw: {width: 32, height: 32, channels: 4}})
    .png({compressionLevel: 9})
    .toFile(path.join(PUBLIC, name))
  console.log(`  ✓ ${name}`)
}

await writePng('cursor-arrow.png', ARROW)
await writePng('cursor-hand.png', HAND)
console.log('\n  Both cursors written to /public.\n')
